const data = [
    {
        id: 1,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528674/Rectangle_1037-2_ncxrzx.png",
        service: 'Website Developement',
        desc: 'Crafting engaging and functional websites tailored to your needs.',
        url: "website-development",
    },
    {
        id: 2,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528715/Rectangle_10370_gzpr9d.png",
        service: 'Digital Marketing',
        desc: 'Boost your online presence and reach your target audience effectively.',
        url: "digital-marketing",
    },
    {
        id: 3,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528678/Rectangle_1037-3_pqe0us.png",
        service: 'Remote Help Desk',
        desc: 'Instant support and solutions for your IT issues, no matter where you are.',
        url: "desk-support",
    },
    {
        id: 4,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712529026/Rectangle_1037y_oxch8m.png",
        service: 'IT System Management',
        desc: 'Streamline your IT infrastructure for seamless operations.',
        url: "itsm",
    },
    {
        id: 5,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528699/Rectangle_1037-7_lwtchz.png",
        service: 'IT Strategy & Consulting',
        desc: 'Strategic guidance to align technology with your business goals.',
        url: "IT-consulting",
    },
    {
        id: 6,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528691/Rectangle_1037-6_cmdwlu.png",
        service: 'Security Management',
        desc: 'Protect your data and systems with robust security measures.',
        url: "security",
    },
    {
        id: 7,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528705/Rectangle_1037-9_qszcjl.png",
        service: 'Cloud Solution',
        desc: 'Harness the power of cloud technology for scalable and efficient operations.',
        url: "services",
    },
    {
        id: 8,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528710/Rectangle_1037gg_w0qlpg.png",
        service: 'Infrastructure Management',
        desc: 'Optimize your IT infrastructure for enhanced performance.',
        url: "infrastructure",
    },
    {
        id: 9,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528682/Rectangle_1037-4_mcueei.png",
        service: 'Backup & Recovery',
        desc: 'Ensure data safety and quick recovery in case of emergencies.',
        url: "backup-and-recovery",
    },
    {
        id: 10,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528688/Rectangle_1037-5_apokfo.png",
        service: 'Patch Management',
        desc: 'Stay up to date and secure with timely software updates.',
        url: "patch-management",
    },
    {
        id: 11,
        img: "https://res.cloudinary.com/dezi0bct4/image/upload/v1712528670/Rectangle_1037-1_igttm2.png",
        service: 'Remote Monitoring',
        desc: 'Monitor your systems remotely for proactive maintenance and issue resolution.',
        url: "remote-monitoring",
    },
]

export default data;